version: "3.7"

services:

  flask:
    build: ./web_app
    container_name: web_app
    restart: always
    environment:
      - APP_NAME=web_app
    expose:
      - 8000

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /home/${USERNAME}/nginx/ssl/:/etc/nginx/ssl
    depends_on:
      - "flask"